[build]
  publish = "public"
  command = "echo 'No build needed'"

[[redirects]]
  from = "/*"
  to = "/mobile.html"
  status = 200
  force = false

[dev]
  command = "node server.cjs"
  port = 8000
  targetPort = 8000
  publish = "public"